# CodeRabbit AI Code Review Configuration
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
    path_filters:
        - '!package-lock.json'
        - '!build/**'
        - '!.svelte-kit/**'
        - '!*.min.js'
        - '!test/data/**'
    tools:
        languagetool:
            disabled_rules:
                - 'EN_COMPOUNDS'

knowledge_base:
    code_guidelines:
        enabled: true
        filePatterns:
            - '**/CLAUDE.md'
