// @ts-check

import eslint from '@eslint/js';
import globals from 'globals';
import { parserOptions } from './.eslintrc.cjs';
import typescriptEslint from 'typescript-eslint';
import eslintPluginPrettier from 'eslint-plugin-prettier';
import eslintPluginSvelte from 'eslint-plugin-svelte';

export default typescriptEslint.config(
    eslint.configs.recommended,
    typescriptEslint.configs.recommended,
    //eslintPluginSvelte.configs.recommended,
    eslintPluginPrettier.configs.recommended,
  );

// js.configs.recommended
// export default typescriptEslint.config(
//     {
//         plugins: {
//             '@typescript-eslint': typescriptEslint.plugin,
//         },
//         languageOptions: {
//             parser: typescriptEslint.parser,
//             parserOptions: {
//                 sourceType: 'module',
//                 ecmaVersion: 2020,
//             },
//             globals: {
//                 browser: true,
//                 es2017: true,
//                 node: true,
//             },
//         },
//         ignores: [
//             '*.cjs',
//             // IDEs
//             ".vscode/*",
//             "!.vscode/extensions.json",
//             "!.vscode/settings.json",
//             // Autogenerated files
//             ".svelte-kit",
//             ".DS_Store",
//             "node_modules",
//             "/build",
//             "/package",
//             "*.local",
//             // Lock files
//             "pnpm-lock.yaml",
//             "package-lock.json",
//             "yarn.lock",
//             "bun.lockb",
//         ],
//     }
// );