/// <reference types="vitest/config" />
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig, type ProxyOptions } from 'vite';
import { emulateProdOnLocalhost } from './src/lib/utils/settings.js';

// Shared proxy config for both dev server and preview server
const apiProxy: Record<string, ProxyOptions> = {
    '/api': {
        target: emulateProdOnLocalhost ? 'https://api.pix.tacocat.com/' : 'https://api.staging-pix.tacocat.com/',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
        configure: (proxy, _options) => {
            proxy.on('error', (err, _req, _res) => {
                console.log('proxy error', err);
            });
            proxy.on('proxyRes', (proxyRes, req, _res) => {
                if (200 !== proxyRes.statusCode) {
                    console.log(
                        'Response from AWS:',
                        proxyRes.statusCode,
                        req.url,
                        JSON.stringify(proxyRes.headers, null, 2),
                    );
                }
            });
        },
    },
};

export default defineConfig({
    plugins: [sveltekit()],
    test: {
        include: ['src/**/*.spec.ts'],

        // Undo spies and stubbed globals between tests, so a test that mocks
        // a browser API the runtime does not provide cannot change what a
        // later one sees. Configured here rather than as an afterEach in each
        // spec, so a new spec inherits the cleanup instead of remembering it.
        restoreMocks: true,
        unstubGlobals: true,

        // Run files and tests in a random order. The suite drives module
        // singletons and stubs globals, so an order dependency is possible to
        // write without noticing; shuffling makes one show up as a failure
        // instead of waiting for an unrelated change to reorder the run.
        sequence: { shuffle: true },

        expect: {
            // Fail a test that asserts nothing. eslint's expect-expect cannot
            // see through a helper holding the assertions, and with vitest's
            // typecheck setting on it accepts expectTypeOf as an assertion even
            // though it is a runtime no-op here.
            requireAssertions: true,
        },

        // A gap-finder, not a gate: no thresholds.
        coverage: {
            // Globbed from the source tree, so a module with no spec at all
            // shows up at 0% rather than not showing up
            include: ['src/**/*.ts'],
            exclude: [
                'src/**/*.spec.ts',
                'src/**/*.e2e.ts', // Playwright specs, which vitest never runs
                'src/lib/test-support/**',
                'src/**/*.d.ts',
                'src/**/$types.ts', // generated by `svelte-kit sync`
            ],

            // .svelte files are out because there is no component test setup;
            // 123 of them at 0% would bury the modules that could be covered today.

            // Options are explicit because vitest rewrites them when it detects
            // an AI agent is running it, giving an agent and a human different
            // tables. skipFull makes the table read as the work list; maxCols
            // stops nine `*Machine.svelte.ts` all eliding to `...ine.svelte.ts`.
            reporter: [
                ['text', { maxCols: 140, skipFull: true }],
                ['text-summary', {}],
                ['html', {}],
            ],
        },
    },
    server: {
        proxy: apiProxy,
    },
    preview: {
        proxy: apiProxy,
    },
});
