#!/usr/bin/env bash
# Block direct edits to CLAUDE.md/AGENTS.md unless source files are also staged.
#
# These files are auto-generated by scripts/build-agent-docs.mjs from
# docs/AGENTS.src.md. Direct edits will be overwritten.
#
# Used by pre-commit hook in .husky/pre-commit

set -euo pipefail

staged_files=$(git diff --cached --name-only)

# If generated files aren't actually staged, nothing to check
if ! echo "$staged_files" | grep -qE "^(CLAUDE|AGENTS)\.md$"; then
    exit 0
fi

# If source file or build script is staged, allow the commit
# (the pre-commit hook will regenerate the output files)
if echo "$staged_files" | grep -qE "(docs/AGENTS\.src\.md|scripts/build-agent-docs\.mjs)$"; then
    exit 0
fi

# Otherwise, block direct edits to generated files
echo "Error: CLAUDE.md and AGENTS.md are auto-generated."
echo "Edit docs/AGENTS.src.md instead, then run: npm run agent-docs"
exit 1
